### ISSUE TITLE
Improve instructions for newbies (and brain-dimmed old-timers)

### ISSUE THREAD

**Issue by netcarver** [outflux3/SettingsFactory#10]
Hi Marc,

Just trying this one out and was stumped by the instructions here for a while...

https://github.com/outflux3/SettingsFactory/blob/2390b2da37e3382d1c89cf0b2aaae6ba744f7175/SettingsFactory.module#L231

I'm over it now - but think these instructions could be improved - maybe with some more specific directions?

1. Create a new page under the admin portion of your site tree, use the admin template when you do.
2. When prompted, select ProcessSettingsFactory as the Process for the page and choose a title to reflect the settings you want to store there.
3. You'll also need to provide the relative path to the schema file the page will use. To get started you can use one of the sample  schema files provided with the module.

Perhaps the relative path to the schema file should default to one of the examples as well to get new users up and running quicker?

Anyway, this looks like a super-useful module. Don't know how I missed it for so long.

**Comment by outflux3** [comment]
thanks - these are similar to the instructions in the readme. Perhaps i should just remove the instructions from the module page, so that I wouldn't need to keep the 2 in sync?

**Comment by netcarver** [comment]
Good point. So maybe just have it point to the readme file for instructions I guess.

**Comment by outflux3** [comment]
I updated the visible instructions in the module to refer to the README.md for in depth instructions.
