### ISSUE TITLE
Remove link to edit Process for non-superusers

### ISSUE THREAD

**Issue by adrianbj** [outflux3/SettingsFactory#4]
Hi @outflux3 - what do you think above removing this for non-superusers? Just because a user has access to the settings page, doesn't mean they should be able to edit the Process page - and of course PW won't actually let them edit that page which makes the link even more confusing for them.

![image](https://user-images.githubusercontent.com/871211/81214072-24929100-8f8c-11ea-81ce-ac9ca7098367.png)

Thanks!

**Comment by outflux3** [comment]
sure, so i just made the change like this:

`			$out = $form->render() . "<p class='version detail'><i class='fa fa-check-square-o'></i> Settings Factory v$moduleInfo[versionStr] | $filepath";
			if($this->wire->user->isSuperuser()) $out .= " | <a href='{$this->wire('page')->editUrl}' target='_blank'>Edit Process Settings</a>";
			$out .= '</p>';`

and need to test it before committing to repo, but should be able to do that soon.

**Comment by outflux3** [comment]
or should i just remove the whole line for non-superusers...

**Comment by adrianbj** [comment]
Honestly I think the entire line should probably be removed - it's irrelevant for non-superusers.

Thanks!

**Comment by outflux3** [comment]
Should be resolved now:
https://github.com/outflux3/SettingsFactory/blob/affa7d0154fe75914b254958afc49747c55ad430/ProcessSettingsFactory.module#L52

**Comment by adrianbj** [comment]
Thanks - that's much better!
